/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package textmusicconverter;

import javax.swing.JOptionPane;

/**
 *
 * @author brendaschussler
 */
public class UserInterface extends javax.swing.JFrame {

    private boolean musicReady = false;

    public boolean isMusicReady() {
        return musicReady;
    }

    public void setMusicReady(boolean musicReady) {
        this.musicReady = musicReady;
    }

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        lSubtitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tInputArea = new javax.swing.JTextArea();
        btnImportFile = new javax.swing.JButton();
        lInitialBpm = new javax.swing.JLabel();
        lInitialInstrument = new javax.swing.JLabel();
        cboxBpm = new javax.swing.JComboBox<>();
        cboxInstrument = new javax.swing.JComboBox<>();
        btnGenerateMusic = new javax.swing.JButton();
        btnPlayMusic = new javax.swing.JButton();
        btnDownloadMusic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTitle.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lTitle.setForeground(new java.awt.Color(0, 102, 153));
        lTitle.setText("Conversor de Texto em Música");

        lSubtitle.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lSubtitle.setForeground(new java.awt.Color(0, 102, 102));
        lSubtitle.setText("Insira abaixo o texto que deseja converter (no máximo 1000 caracteres)");

        tInputArea.setColumns(20);
        tInputArea.setRows(5);
        jScrollPane1.setViewportView(tInputArea);

        btnImportFile.setBackground(new java.awt.Color(0, 102, 102));
        btnImportFile.setForeground(new java.awt.Color(255, 255, 255));
        btnImportFile.setText("Importar arquivo de texto ");

        lInitialBpm.setFont(new java.awt.Font("Liberation Sans", 3, 16)); // NOI18N
        lInitialBpm.setText("BPM inicial ");

        lInitialInstrument.setFont(new java.awt.Font("Liberation Sans", 3, 16)); // NOI18N
        lInitialInstrument.setText("Instrumento inicial ");

        cboxBpm.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cboxBpm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRAVE", "LARGO", "LARGHETTO", "LENTO", "ADAGIO", "ADAGIETTO", "ANDANTE", "ANDANTINO", "MODERATO", "ALLEGRETTO", "ALLEGRO", "VIVACE", "PRESTO", "PRETISSIMO" }));
        cboxBpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxBpmActionPerformed(evt);
            }
        });

        cboxInstrument.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cboxInstrument.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGenerateMusic.setBackground(new java.awt.Color(0, 102, 102));
        btnGenerateMusic.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnGenerateMusic.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateMusic.setText("Gerar música");
        btnGenerateMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateMusicActionPerformed(evt);
            }
        });

        btnPlayMusic.setBackground(new java.awt.Color(0, 102, 102));
        btnPlayMusic.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnPlayMusic.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayMusic.setText("Reproduzir música");
        btnPlayMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMusicActionPerformed(evt);
            }
        });

        btnDownloadMusic.setBackground(new java.awt.Color(0, 102, 102));
        btnDownloadMusic.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnDownloadMusic.setForeground(new java.awt.Color(255, 255, 255));
        btnDownloadMusic.setText("Fazer download da música");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGenerateMusic)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lSubtitle)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnImportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lInitialInstrument)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboxInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lInitialBpm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxBpm, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPlayMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDownloadMusic)
                        .addGap(315, 315, 315))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lTitle)
                .addGap(18, 18, 18)
                .addComponent(lSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lInitialBpm)
                    .addComponent(cboxBpm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lInitialInstrument)
                    .addComponent(cboxInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerateMusic)
                .addGap(29, 29, 29)
                .addComponent(btnPlayMusic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDownloadMusic)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateMusicActionPerformed
        if (tInputArea.getText().length() > 0) {
            InputParser.setUserInput(tInputArea.getText()); //userInput recebe o que foi digitado na caixa de texto
            setMusicReady(false);
            InputParser.userInputParser();
            MusicAssembler.generateAudioString();
            setMusicReady(true);
            JOptionPane.showMessageDialog(rootPane, "Sua música foi gerada com sucesso!", "UHUUU", JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(rootPane, InputParser.getUserInput());
            //JOptionPane.showMessageDialog(rootPane, SoundHandler.getBpmIndexDefault()); //teste do index bpm ok 
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não é possível gerar música de um input vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerateMusicActionPerformed

    private void btnPlayMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMusicActionPerformed
        if (isMusicReady()) {
            MusicAssembler.playAudio();
        } else {
            JOptionPane.showMessageDialog(rootPane, "A música ainda não foi gerada! Aguarde...", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPlayMusicActionPerformed

    private void cboxBpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxBpmActionPerformed
        SoundHandler.setBpmIndexDefault(cboxBpm.getSelectedIndex()); // pega o indice do bpm (0 a 13) p o vetor
    }//GEN-LAST:event_cboxBpmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownloadMusic;
    private javax.swing.JButton btnGenerateMusic;
    private javax.swing.JButton btnImportFile;
    private javax.swing.JButton btnPlayMusic;
    private javax.swing.JComboBox<String> cboxBpm;
    private javax.swing.JComboBox<String> cboxInstrument;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lInitialBpm;
    private javax.swing.JLabel lInitialInstrument;
    private javax.swing.JLabel lSubtitle;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextArea tInputArea;
    // End of variables declaration//GEN-END:variables
}
